from app.routes.root import *
from app.routes.auth import *
from app.routes.user_route import *
from app.routes.staff_route import *
from app.routes.admin_route import *
from app.routes.supplier_route import *
from app.routes.deliveryMan_route import *
from app.routes.food_route import *
from app.routes.notify_route import *
from app.routes.comment_route import *
from app.routes.foodIdea_route import *
from app.routes.foodGroup_route import *
from app.routes.upload_file_route import *
from app.routes.topic_route import *
from app.routes.role_route import *
from app.routes.address_route import *
from app.routes.order_route import *
from app.routes.favorited_food_route import *
from app.routes.cart_route import *
from app.routes.review_route import *