from app.routes.root import *
from app.routes.auth import *
from app.routes.user_route import *
from app.routes.admin_route import *
from app.routes.food_route import *
from app.routes.recipe_route import *
from app.routes.favorite_route import *
from app.routes.comment_route import *
from app.routes.foodIdea_route import *
from app.routes.foodGroup_route import *
from app.routes.upload_file_route import *
from app.routes.topic_route import *